#!/usr/bin/python

s="CATTCGCGCTGAAAGGCGAATCGTTACCCTTATGCCAGTAGACGAGATCCCATATAAGGTCAGTATCCAACCCATAGACACATGTTTTGTTGAGCCCGGAAGTCCACGTGCTTCTTGTCGATTATACTCTTTTCCACCAAACTTTCATCGTTAGTCCAGAGCTATAGAGAACATCAAACTGTCCAAAGCAGAGAGACTATCGGTGACGTGTGGACTCCACTCCCATTACGCGTTAGCTCGTATTCCCGTGAGTTCTAATTTAGCAGGGGGGGTCTCAGCTTTTGTCTCTCCTTTCTCCGCCTGGGGTGAGAACGTGTACTTGCCTCGGTCATAATGTGGCTCATTTGTGTCAGGCTAGGGCCTACCCGGGACGGCGTTTAGTATCTGAGTGTTCCAGAAACATCTTACCCTAAAATATACTCTCAAAGGTCTTCATCCACATCGTCAAGCGGCGATATGCGGTCCAGAGCCACGCGTACACCCTAGCGCTTGGCTGCGAATTGCCACGGAGCTCGACATTCGTGGAACCCCGGTGCACGATTGGACAGGGTGCGCTGGAAGAGTACCCAAAGGCTACGAAACCCTTACCGGTCCTGCTGAGTCAAGAGCATCTTAGGCATTCATAAGTGACGTTACCATCGGTTGGGTTGTGTAATCACCTGAAACCAGGCCACCAGAGATAGTATCGGTAGCTCCGCGACGTGTCGTCCCGTCACATGCCCCATGTGGACAGGTGCCCTACGAAAAACGTAATATCCGATACCACAGAACTCTGTCCCTTTACCATAGATCGGGATGTTATATTTTCTAAATAAAGGGAAAAGAGAAGTTAGAGTTAGGACAAATCGTGACCGCGCTGCATCCGTGAGTCTCGAAATGTATAACTT"

a=0
c=0
g=0
t=0

for n in s:
    if n=="A":
        a+=1
    if n=="C":
        c+=1
    if n=="G":
        g+=1
    if n=="T":
        t+=1

print a, c, g, t
